package model;
// Generated May 13, 2015 2:35:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Appointments generated by hbm2java
 */
@Entity
@Table(name="appointments"
    ,catalog="docnet"
)
public class Appointments  implements java.io.Serializable {


     private Integer appointmentid;
     private long pateientidentifier;
     private int docid;
     private String timeofday;
     private Date starttime;
     private Date endtime;
     private Date date;

    public Appointments() {
    }

    public Appointments(long pateientidentifier, int docid, String timeofday, Date starttime, Date endtime, Date date) {
       this.pateientidentifier = pateientidentifier;
       this.docid = docid;
       this.timeofday = timeofday;
       this.starttime = starttime;
       this.endtime = endtime;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="appointmentid", nullable=false)
    public Integer getAppointmentid() {
        return this.appointmentid;
    }
    
    public void setAppointmentid(Integer appointmentid) {
        this.appointmentid = appointmentid;
    }

    
    @Column(name="pateientidentifier", nullable=false)
    public long getPateientidentifier() {
        return this.pateientidentifier;
    }
    
    public void setPateientidentifier(long pateientidentifier) {
        this.pateientidentifier = pateientidentifier;
    }

    
    @Column(name="docid", nullable=false)
    public int getDocid() {
        return this.docid;
    }
    
    public void setDocid(int docid) {
        this.docid = docid;
    }

    
    @Column(name="timeofday", nullable=false, length=250)
    public String getTimeofday() {
        return this.timeofday;
    }
    
    public void setTimeofday(String timeofday) {
        this.timeofday = timeofday;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="starttime", nullable=false, length=8)
    public Date getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="endtime", nullable=false, length=8)
    public Date getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


