package model;
// Generated May 13, 2015 2:35:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Blogs generated by hbm2java
 */
@Entity
@Table(name="blogs"
    ,catalog="docnet"
)
public class Blogs  implements java.io.Serializable {


     private Integer id;
     private String blogname;
     private Date blogdate;
     private String blogimage;
     private String blogcontent;

    public Blogs() {
    }

    public Blogs(String blogname, Date blogdate, String blogimage, String blogcontent) {
       this.blogname = blogname;
       this.blogdate = blogdate;
       this.blogimage = blogimage;
       this.blogcontent = blogcontent;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="blogname", nullable=false, length=250)
    public String getBlogname() {
        return this.blogname;
    }
    
    public void setBlogname(String blogname) {
        this.blogname = blogname;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="blogdate", nullable=false, length=10)
    public Date getBlogdate() {
        return this.blogdate;
    }
    
    public void setBlogdate(Date blogdate) {
        this.blogdate = blogdate;
    }

    
    @Column(name="blogimage", nullable=false, length=250)
    public String getBlogimage() {
        return this.blogimage;
    }
    
    public void setBlogimage(String blogimage) {
        this.blogimage = blogimage;
    }

    
    @Column(name="blogcontent", nullable=false, length=3000)
    public String getBlogcontent() {
        return this.blogcontent;
    }
    
    public void setBlogcontent(String blogcontent) {
        this.blogcontent = blogcontent;
    }




}


