package model;
// Generated May 13, 2015 2:35:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Doctors generated by hbm2java
 */
@Entity
@Table(name="doctors"
    ,catalog="docnet"
    , uniqueConstraints = @UniqueConstraint(columnNames="pmdc_id") 
)
public class Doctors  implements java.io.Serializable {


     private int id;
     private String doctorname;
     private String doctordepartment;
     private String doctorimage;
     private String email;
     private String city;
     private String address;
     private Integer pmdcId;
     private Integer contact;
     

    public Doctors() {
    }

	
    public Doctors(int id, Integer contact,String doctorname, String doctordepartment, String doctorimage,String email, String city, String address) {
        this.id = id;
        this.doctorname = doctorname;
        this.doctordepartment = doctordepartment;
        this.doctorimage = doctorimage;
        this.email = email;
        this.city = city;
        this.address = address;
        this.contact = contact;
    }
    public Doctors(int id, String doctorname, String doctordepartment, String doctorimage, String city, String address, Integer pmdcId, Integer contact) {
       this.id = id;
       this.doctorname = doctorname;
       this.doctordepartment = doctordepartment;
       this.doctorimage = doctorimage;
       this.email = email;
       this.city = city;
       this.address = address;
       this.pmdcId = pmdcId;
       this.contact = contact;
    }
   
     @Id 

    
    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="doctorname", nullable=false, length=50)
    public String getDoctorname() {
        return this.doctorname;
    }
    
    public void setDoctorname(String doctorname) {
        this.doctorname = doctorname;
    }

    @Column(name="email", length = 45)
    public String getEmail() {
        return this.email;
    }
     
    
    public void setEmail(String email) {
        this.email = email;
    }

     
     @Column(name="contact")
     
     public Integer getContact() {
        return this.contact;
    }
      public void setContact(Integer contact) {
        this.contact = contact;
    }

     
    
    @Column(name="doctordepartment", nullable=false, length=50)
    public String getDoctordepartment() {
        return this.doctordepartment;
    }
    
    public void setDoctordepartment(String doctordepartment) {
        this.doctordepartment = doctordepartment;
    }

    
    @Column(name="doctorimage", nullable=false, length=50)
    public String getDoctorimage() {
        return this.doctorimage;
    }
    
    public void setDoctorimage(String doctorimage) {
        this.doctorimage = doctorimage;
    }

    
    @Column(name="city", nullable=false, length=45)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="address", nullable=false, length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="pmdc_id", unique=true)
    public Integer getPmdcId() {
        return this.pmdcId;
    }
    
    public void setPmdcId(Integer pmdcId) {
        this.pmdcId = pmdcId;
    }




}


