package model;
// Generated May 13, 2015 2:35:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Events generated by hbm2java
 */
@Entity
@Table(name="events"
    ,catalog="docnet"
)
public class Events  implements java.io.Serializable {


     private int id;
     private String eventname;
     private String description;
     private String eventlocation;
     private Date eventstime;

    public Events() {
    }

    public Events(int id, String eventname, String description, String eventlocation, Date eventstime) {
       this.id = id;
       this.eventname = eventname;
       this.description = description;
       this.eventlocation = eventlocation;
       this.eventstime = eventstime;
    }
   
     @Id 

    
    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="eventname", nullable=false, length=45)
    public String getEventname() {
        return this.eventname;
    }
    
    public void setEventname(String eventname) {
        this.eventname = eventname;
    }

    
    @Column(name="description", nullable=false, length=3000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="eventlocation", nullable=false, length=1000)
    public String getEventlocation() {
        return this.eventlocation;
    }
    
    public void setEventlocation(String eventlocation) {
        this.eventlocation = eventlocation;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="eventstime", nullable=false, length=8)
    public Date getEventstime() {
        return this.eventstime;
    }
    
    public void setEventstime(Date eventstime) {
        this.eventstime = eventstime;
    }




}


