package model;
// Generated May 13, 2015 2:35:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Logintable generated by hbm2java
 */
@Entity
@Table(name="logintable"
    ,catalog="docnet"
)
public class Logintable  implements java.io.Serializable {


     private Long cnic;
     private String password;
     private String status;

    public Logintable() {
    }

    public Logintable(Long cnic, String password, String status) {
       this.cnic = cnic;
       this.password = password;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="cnic", nullable=false)
    public Long getCnic() {
        return this.cnic;
    }
    
    public void setCnic(Long cnic) {
        this.cnic = cnic;
    }

    
    @Column(name="password", nullable=false, length=11)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="status", nullable=false, length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


