package model;
// Generated May 13, 2015 2:35:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Timings generated by hbm2java
 */
@Entity
@Table(name="timings"
    ,catalog="docnet"
)
public class Timings  implements java.io.Serializable {


     private int id;
     private Date mondaystartM;
     private Date mondayendM;
     private String mondayLocM;
     private Date tuesdaystartM;
     private Date tuesdayendM;
     private String tuesdayLocM;
     private Date wednesdaystartM;
     private Date wednesdayendM;
     private String wednesdayLocM;
     private Date thursdaystartM;
     private Date thursdayendM;
     private String thursdayLocM;
     private Date fridaystartM;
     private Date fridayendM;
     private String fridayLocM;
     private Date saturdaystartM;
     private Date saturdayendM;
     private String saturdayLocM;
     private Date sundaystartM;
     private Date sundayendM;
     private String sundayLocM;
     private Date mondaystartE;
     private Date mondayendE;
     private String mondayLocE;
     private Date tuesdaystartE;
     private Date tuesdayendE;
     private String tuesdayLocE;
     private Date wednesdaystartE;
     private Date wednesdayendE;
     private String wednesdayLocE;
     private Date thursdaystartE;
     private Date thursdayendE;
     private String thursdayLocE;
     private Date fridaystartE;
     private Date fridayendE;
     private String fridayLocE;
     private Date saturdaystartE;
     private Date saturdayendE;
     private String saturdayLocE;
     private Date sundaystartE;
     private Date sundayendE;
     private String sundayLocE;

    public Timings() {
    }

	
    public Timings(int id) {
        this.id = id;
    }
    public Timings(int id, Date mondaystartM, Date mondayendM, String mondayLocM, Date tuesdaystartM, Date tuesdayendM, String tuesdayLocM, Date wednesdaystartM, Date wednesdayendM, String wednesdayLocM, Date thursdaystartM, Date thursdayendM, String thursdayLocM, Date fridaystartM, Date fridayendM, String fridayLocM, Date saturdaystartM, Date saturdayendM, String saturdayLocM, Date sundaystartM, Date sundayendM, String sundayLocM, Date mondaystartE, Date mondayendE, String mondayLocE, Date tuesdaystartE, Date tuesdayendE, String tuesdayLocE, Date wednesdaystartE, Date wednesdayendE, String wednesdayLocE, Date thursdaystartE, Date thursdayendE, String thursdayLocE, Date fridaystartE, Date fridayendE, String fridayLocE, Date saturdaystartE, Date saturdayendE, String saturdayLocE, Date sundaystartE, Date sundayendE, String sundayLocE) {
       this.id = id;
       this.mondaystartM = mondaystartM;
       this.mondayendM = mondayendM;
       this.mondayLocM = mondayLocM;
       this.tuesdaystartM = tuesdaystartM;
       this.tuesdayendM = tuesdayendM;
       this.tuesdayLocM = tuesdayLocM;
       this.wednesdaystartM = wednesdaystartM;
       this.wednesdayendM = wednesdayendM;
       this.wednesdayLocM = wednesdayLocM;
       this.thursdaystartM = thursdaystartM;
       this.thursdayendM = thursdayendM;
       this.thursdayLocM = thursdayLocM;
       this.fridaystartM = fridaystartM;
       this.fridayendM = fridayendM;
       this.fridayLocM = fridayLocM;
       this.saturdaystartM = saturdaystartM;
       this.saturdayendM = saturdayendM;
       this.saturdayLocM = saturdayLocM;
       this.sundaystartM = sundaystartM;
       this.sundayendM = sundayendM;
       this.sundayLocM = sundayLocM;
       this.mondaystartE = mondaystartE;
       this.mondayendE = mondayendE;
       this.mondayLocE = mondayLocE;
       this.tuesdaystartE = tuesdaystartE;
       this.tuesdayendE = tuesdayendE;
       this.tuesdayLocE = tuesdayLocE;
       this.wednesdaystartE = wednesdaystartE;
       this.wednesdayendE = wednesdayendE;
       this.wednesdayLocE = wednesdayLocE;
       this.thursdaystartE = thursdaystartE;
       this.thursdayendE = thursdayendE;
       this.thursdayLocE = thursdayLocE;
       this.fridaystartE = fridaystartE;
       this.fridayendE = fridayendE;
       this.fridayLocE = fridayLocE;
       this.saturdaystartE = saturdaystartE;
       this.saturdayendE = saturdayendE;
       this.saturdayLocE = saturdayLocE;
       this.sundaystartE = sundaystartE;
       this.sundayendE = sundayendE;
       this.sundayLocE = sundayLocE;
    }
   
     @Id 

    
    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="MondaystartM", length=8)
    public Date getMondaystartM() {
        return this.mondaystartM;
    }
    
    public void setMondaystartM(Date mondaystartM) {
        this.mondaystartM = mondaystartM;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="MondayendM", length=8)
    public Date getMondayendM() {
        return this.mondayendM;
    }
    
    public void setMondayendM(Date mondayendM) {
        this.mondayendM = mondayendM;
    }

    
    @Column(name="MondayLocM", length=20)
    public String getMondayLocM() {
        return this.mondayLocM;
    }
    
    public void setMondayLocM(String mondayLocM) {
        this.mondayLocM = mondayLocM;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="TuesdaystartM", length=8)
    public Date getTuesdaystartM() {
        return this.tuesdaystartM;
    }
    
    public void setTuesdaystartM(Date tuesdaystartM) {
        this.tuesdaystartM = tuesdaystartM;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="TuesdayendM", length=8)
    public Date getTuesdayendM() {
        return this.tuesdayendM;
    }
    
    public void setTuesdayendM(Date tuesdayendM) {
        this.tuesdayendM = tuesdayendM;
    }

    
    @Column(name="TuesdayLocM", length=20)
    public String getTuesdayLocM() {
        return this.tuesdayLocM;
    }
    
    public void setTuesdayLocM(String tuesdayLocM) {
        this.tuesdayLocM = tuesdayLocM;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="WednesdaystartM", length=8)
    public Date getWednesdaystartM() {
        return this.wednesdaystartM;
    }
    
    public void setWednesdaystartM(Date wednesdaystartM) {
        this.wednesdaystartM = wednesdaystartM;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="WednesdayendM", length=8)
    public Date getWednesdayendM() {
        return this.wednesdayendM;
    }
    
    public void setWednesdayendM(Date wednesdayendM) {
        this.wednesdayendM = wednesdayendM;
    }

    
    @Column(name="WednesdayLocM", length=20)
    public String getWednesdayLocM() {
        return this.wednesdayLocM;
    }
    
    public void setWednesdayLocM(String wednesdayLocM) {
        this.wednesdayLocM = wednesdayLocM;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="ThursdaystartM", length=8)
    public Date getThursdaystartM() {
        return this.thursdaystartM;
    }
    
    public void setThursdaystartM(Date thursdaystartM) {
        this.thursdaystartM = thursdaystartM;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="ThursdayendM", length=8)
    public Date getThursdayendM() {
        return this.thursdayendM;
    }
    
    public void setThursdayendM(Date thursdayendM) {
        this.thursdayendM = thursdayendM;
    }

    
    @Column(name="ThursdayLocM", length=20)
    public String getThursdayLocM() {
        return this.thursdayLocM;
    }
    
    public void setThursdayLocM(String thursdayLocM) {
        this.thursdayLocM = thursdayLocM;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="FridaystartM", length=8)
    public Date getFridaystartM() {
        return this.fridaystartM;
    }
    
    public void setFridaystartM(Date fridaystartM) {
        this.fridaystartM = fridaystartM;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="FridayendM", length=8)
    public Date getFridayendM() {
        return this.fridayendM;
    }
    
    public void setFridayendM(Date fridayendM) {
        this.fridayendM = fridayendM;
    }

    
    @Column(name="FridayLocM", length=20)
    public String getFridayLocM() {
        return this.fridayLocM;
    }
    
    public void setFridayLocM(String fridayLocM) {
        this.fridayLocM = fridayLocM;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="SaturdaystartM", length=8)
    public Date getSaturdaystartM() {
        return this.saturdaystartM;
    }
    
    public void setSaturdaystartM(Date saturdaystartM) {
        this.saturdaystartM = saturdaystartM;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="SaturdayendM", length=8)
    public Date getSaturdayendM() {
        return this.saturdayendM;
    }
    
    public void setSaturdayendM(Date saturdayendM) {
        this.saturdayendM = saturdayendM;
    }

    
    @Column(name="SaturdayLocM", length=20)
    public String getSaturdayLocM() {
        return this.saturdayLocM;
    }
    
    public void setSaturdayLocM(String saturdayLocM) {
        this.saturdayLocM = saturdayLocM;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="SundaystartM", length=8)
    public Date getSundaystartM() {
        return this.sundaystartM;
    }
    
    public void setSundaystartM(Date sundaystartM) {
        this.sundaystartM = sundaystartM;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="SundayendM", length=8)
    public Date getSundayendM() {
        return this.sundayendM;
    }
    
    public void setSundayendM(Date sundayendM) {
        this.sundayendM = sundayendM;
    }

    
    @Column(name="SundayLocM", length=20)
    public String getSundayLocM() {
        return this.sundayLocM;
    }
    
    public void setSundayLocM(String sundayLocM) {
        this.sundayLocM = sundayLocM;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="MondaystartE", length=8)
    public Date getMondaystartE() {
        return this.mondaystartE;
    }
    
    public void setMondaystartE(Date mondaystartE) {
        this.mondaystartE = mondaystartE;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="MondayendE", length=8)
    public Date getMondayendE() {
        return this.mondayendE;
    }
    
    public void setMondayendE(Date mondayendE) {
        this.mondayendE = mondayendE;
    }

    
    @Column(name="MondayLocE", length=20)
    public String getMondayLocE() {
        return this.mondayLocE;
    }
    
    public void setMondayLocE(String mondayLocE) {
        this.mondayLocE = mondayLocE;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="TuesdaystartE", length=8)
    public Date getTuesdaystartE() {
        return this.tuesdaystartE;
    }
    
    public void setTuesdaystartE(Date tuesdaystartE) {
        this.tuesdaystartE = tuesdaystartE;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="TuesdayendE", length=8)
    public Date getTuesdayendE() {
        return this.tuesdayendE;
    }
    
    public void setTuesdayendE(Date tuesdayendE) {
        this.tuesdayendE = tuesdayendE;
    }

    
    @Column(name="TuesdayLocE", length=20)
    public String getTuesdayLocE() {
        return this.tuesdayLocE;
    }
    
    public void setTuesdayLocE(String tuesdayLocE) {
        this.tuesdayLocE = tuesdayLocE;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="WednesdaystartE", length=8)
    public Date getWednesdaystartE() {
        return this.wednesdaystartE;
    }
    
    public void setWednesdaystartE(Date wednesdaystartE) {
        this.wednesdaystartE = wednesdaystartE;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="WednesdayendE", length=8)
    public Date getWednesdayendE() {
        return this.wednesdayendE;
    }
    
    public void setWednesdayendE(Date wednesdayendE) {
        this.wednesdayendE = wednesdayendE;
    }

    
    @Column(name="WednesdayLocE", length=20)
    public String getWednesdayLocE() {
        return this.wednesdayLocE;
    }
    
    public void setWednesdayLocE(String wednesdayLocE) {
        this.wednesdayLocE = wednesdayLocE;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="ThursdaystartE", length=8)
    public Date getThursdaystartE() {
        return this.thursdaystartE;
    }
    
    public void setThursdaystartE(Date thursdaystartE) {
        this.thursdaystartE = thursdaystartE;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="ThursdayendE", length=8)
    public Date getThursdayendE() {
        return this.thursdayendE;
    }
    
    public void setThursdayendE(Date thursdayendE) {
        this.thursdayendE = thursdayendE;
    }

    
    @Column(name="ThursdayLocE", length=20)
    public String getThursdayLocE() {
        return this.thursdayLocE;
    }
    
    public void setThursdayLocE(String thursdayLocE) {
        this.thursdayLocE = thursdayLocE;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="FridaystartE", length=8)
    public Date getFridaystartE() {
        return this.fridaystartE;
    }
    
    public void setFridaystartE(Date fridaystartE) {
        this.fridaystartE = fridaystartE;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="FridayendE", length=8)
    public Date getFridayendE() {
        return this.fridayendE;
    }
    
    public void setFridayendE(Date fridayendE) {
        this.fridayendE = fridayendE;
    }

    
    @Column(name="FridayLocE", length=20)
    public String getFridayLocE() {
        return this.fridayLocE;
    }
    
    public void setFridayLocE(String fridayLocE) {
        this.fridayLocE = fridayLocE;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="SaturdaystartE", length=8)
    public Date getSaturdaystartE() {
        return this.saturdaystartE;
    }
    
    public void setSaturdaystartE(Date saturdaystartE) {
        this.saturdaystartE = saturdaystartE;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="SaturdayendE", length=8)
    public Date getSaturdayendE() {
        return this.saturdayendE;
    }
    
    public void setSaturdayendE(Date saturdayendE) {
        this.saturdayendE = saturdayendE;
    }

    
    @Column(name="SaturdayLocE", length=20)
    public String getSaturdayLocE() {
        return this.saturdayLocE;
    }
    
    public void setSaturdayLocE(String saturdayLocE) {
        this.saturdayLocE = saturdayLocE;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="SundaystartE", length=8)
    public Date getSundaystartE() {
        return this.sundaystartE;
    }
    
    public void setSundaystartE(Date sundaystartE) {
        this.sundaystartE = sundaystartE;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="SundayendE", length=8)
    public Date getSundayendE() {
        return this.sundayendE;
    }
    
    public void setSundayendE(Date sundayendE) {
        this.sundayendE = sundayendE;
    }

    
    @Column(name="SundayLocE", length=20)
    public String getSundayLocE() {
        return this.sundayLocE;
    }
    
    public void setSundayLocE(String sundayLocE) {
        this.sundayLocE = sundayLocE;
    }




}


